### ISSUE TITLE
Remove microphone-driver.js file from repo since it's unused

### ISSUE THREAD

**Issue by anil614sagar** [krypten/zetta-microphone-raspberrypi-driver#1]
Dear @krypten ,

I see microphone-driver.js and microphone_driver.js files in your repo and i believe only microphone_driver.js file is used. 

So please remove the other file.

Cheers,
AniL Sagar

**Comment by krypten** [comment]
Hi Anil sir,

Thank you.

**Comment by anil614sagar** [comment]
Awesome work @krypten , I will test the driver with physical devices and get back to you. Keep it up.
